---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hacker.
--- DateTime: 2024/6/12 23:13
---
if(redis.call('get',KEYS[1] == ARGV[1]))then
    return redis.call('del',KEYS[1])
end
return 0